general:
  threads: 1
  log-level: 'error'
  inputfile:
    para: 'para.root'
    ana: 'simu.root'
    simu: ''
    online: ''
  outputfile:
    para: 'para.root'
    ana: 'digi.root'
    simu: 'simu.root'
    online: ''
  analysis:
    event: [0, 0]
  simulation:
    material-file: 'media_r3b.geo'
    simu-engine: 'TGeant4'
    store-trajectory: off
    event:
      number: 10
      print: 2
    particle-gun:
      particle-name: 'neutron'
      multiplicity: 1
      position: [0., 0., 0.]
      theta: [0., 3.]
      phi: [0., 360.]
      energy: [1., 1.]
    
cave:
  simulation:
    status: on
    geo-file: 'r3b_cave.geo'

neuland:
  simulation:
    status: off
    position: [0., 0., 1650.]
    nDP: 13
  analysis:
    digitizer:
      paddle: 'neuland' # either 'neuland' or 'mock'
      channel: 'tamex' # either 'tamex' or 'tacquila' or 'mock'
      hit-par: ''
